GET http://localhost:5000/api/v1/

###

POST  http://localhost:5000/api/v1/add-income
Content-Type: application/json

{
    "title":"prvi",
    "amount":100,
    "type":"dobar", 
    "date":"10-10-2020", 
    "category":"doabr",
    "description":"nema"     
}